name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version:  |
          3.1.x
          5.x
          6.x
          7.x
          8.x
          9.x
    - run: dotnet test
      working-directory: ./Sample/UnitTest_netcoreapp3.1
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net5.0
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net6.0
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net7.0
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net8.0
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net9.0
