name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet test
      working-directory: ./Sample/UnitTest_netcoreapp3.1
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net5.0
