name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - run: dotnet test
      working-directory: ./Sample/UnitTest_netcoreapp3.1
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net5.0
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net6.0
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net7.0
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net8.0
    - run: dotnet test
      working-directory: ./Sample/UnitTest_net9.0
